INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (1, 1 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (1, 2 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (1, 3 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (1, 4 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (1, 5 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (1, 6 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (1, 7 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (2, 8 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (2, 9 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (2, 10 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (2, 11 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (2, 12 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (2, 13 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (2, 14 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (3, 15 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (3, 16 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (3, 17 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (3, 18 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (3, 19 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (3, 20 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (3, 21 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (4, 22 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (4, 23 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (4, 24 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (4, 25 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (4, 26 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (4, 27 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (4, 28 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (5, 29 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (5, 30 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (5, 31 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (5, 32 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (5, 33 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (5, 34 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (5, 35 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (6, 36 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (6, 37 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (6, 38 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (6, 39 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (6, 40 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (6, 41 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (6, 42 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (7, 43 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (7, 44 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (7, 45 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (7, 46 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (7, 47 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (7, 48 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (7, 49 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (8, 50 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (8, 51 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (8, 52 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (8, 53 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (8, 54 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (8, 55 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (8, 56 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (9, 57 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (9, 58 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (9, 59 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (9, 60 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (9, 61 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (9, 62 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (9, 63 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (10,64 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (10,65 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (10,66 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (10,67 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (10,68 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (10,69 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (10,70 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (11,71 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (11,72 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (11,73 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (11,74 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (11,75 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (11,76 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (11,77 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (12,78 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (12,79 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (12,80 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (12,81 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (12,82 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (12,83 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (12,84 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (13,85 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (13,86 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (13,87 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (13,88 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (13,89 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (13,90 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (13,91 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (14,92 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (14,93 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (14,94 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (14,95 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (14,96 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (14,97 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (14,98 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (15,99 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (15,100 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (15,101 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (15,102 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (15,103 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (15,104 );
INSERT INTO availability_working_day( availability_availability_id, days_working_day_id) VALUES (15,105 );
                                                                                                   