DROP TABLE address CASCADE;
DROP TABLE availability CASCADE;
DROP TABLE business CASCADE;
DROP TABLE availability_working_day CASCADE;
DROP TABLE category CASCADE;
DROP TABLE contact CASCADE;
DROP TABLE reservation CASCADE;
DROP TABLE users CASCADE;
DROP TABLE working_day CASCADE;
DROP TABLE treatment CASCADE;
DROP TABLE medecin CASCADE;






